"""agent accounts and request log agent

Revision ID: c0f6dac11f0c
Revises: c03a822bc23a
Create Date: 2026-10-07 01:44:03.328013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0f6dac11f0c'
down_revision: Union[str, Sequence[str], None] = 'c03a822bc23a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_accounts_username'), 'agent_accounts', ['username'], unique=True)
    op.add_column('api_request_log', sa.Column('agent', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_api_request_log_agent'), 'api_request_log', ['agent'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_request_log_agent'), table_name='api_request_log')
    op.drop_column('api_request_log', 'agent')
    op.drop_index(op.f('ix_agent_accounts_username'), table_name='agent_accounts')
    op.drop_table('agent_accounts')
    # ### end Alembic commands ###
