"""initial schema

Revision ID: c03a822bc23a
Revises: 
Create Date: 2026-10-07 01:12:31.166800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c03a822bc23a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('requisite', sa.String(length=64), nullable=False),
    sa.Column('requisite_suffix', sa.String(length=4), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('scenario', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_idempotency_key'), 'payments', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_payments_requisite_suffix'), 'payments', ['requisite_suffix'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_table('payout_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pin', sa.String(length=12), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('currency', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('scenario', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('fio', sa.String(length=255), nullable=True),
    sa.Column('exchange_id', sa.Integer(), nullable=True),
    sa.Column('otp_needed', sa.Boolean(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('commission', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('blocked_point_id', sa.String(length=64), nullable=True),
    sa.Column('blocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payout_codes_pin'), 'payout_codes', ['pin'], unique=True)
    op.create_index(op.f('ix_payout_codes_status'), 'payout_codes', ['status'], unique=False)
    op.create_table('scenario_settings',
    sa.Column('suffix', sa.String(length=4), nullable=False),
    sa.Column('delay_seconds', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('suffix')
    )
    op.create_table('api_request_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('endpoint', sa.String(length=16), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('client', sa.String(length=64), nullable=True),
    sa.Column('payment_id', sa.String(length=36), nullable=True),
    sa.Column('requisite', sa.String(length=64), nullable=True),
    sa.Column('request_body', sa.Text(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_request_log_endpoint'), 'api_request_log', ['endpoint'], unique=False)
    op.create_index(op.f('ix_api_request_log_payment_id'), 'api_request_log', ['payment_id'], unique=False)
    op.create_index(op.f('ix_api_request_log_requisite'), 'api_request_log', ['requisite'], unique=False)
    op.create_index(op.f('ix_api_request_log_timestamp'), 'api_request_log', ['timestamp'], unique=False)
    op.create_table('payment_status_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_status_history_payment_id'), 'payment_status_history', ['payment_id'], unique=False)
    op.create_table('payout_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=32), nullable=False),
    sa.Column('point_id', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('balance_after', sa.Integer(), nullable=True),
    sa.Column('client_timestamp', sa.String(length=64), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['code_id'], ['payout_codes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payout_events_code_id'), 'payout_events', ['code_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payout_events_code_id'), table_name='payout_events')
    op.drop_table('payout_events')
    op.drop_index(op.f('ix_payment_status_history_payment_id'), table_name='payment_status_history')
    op.drop_table('payment_status_history')
    op.drop_index(op.f('ix_api_request_log_timestamp'), table_name='api_request_log')
    op.drop_index(op.f('ix_api_request_log_requisite'), table_name='api_request_log')
    op.drop_index(op.f('ix_api_request_log_payment_id'), table_name='api_request_log')
    op.drop_index(op.f('ix_api_request_log_endpoint'), table_name='api_request_log')
    op.drop_table('api_request_log')
    op.drop_table('scenario_settings')
    op.drop_index(op.f('ix_payout_codes_status'), table_name='payout_codes')
    op.drop_index(op.f('ix_payout_codes_pin'), table_name='payout_codes')
    op.drop_table('payout_codes')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_requisite_suffix'), table_name='payments')
    op.drop_index(op.f('ix_payments_idempotency_key'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
